"""configuraçoes alteradas para rodar o httpdigestauth

Revision ID: 488f87eeaf22
Revises: eccae505896f
Create Date: 2021-07-20 18:01:39.162466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488f87eeaf22'
down_revision = 'eccae505896f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=511), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=511), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
