"""configuraçoes alteradas para rodar o jwt

Revision ID: 93609805a63a
Revises: 488f87eeaf22
Create Date: 2021-07-20 18:22:17.464002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93609805a63a'
down_revision = '488f87eeaf22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=511), nullable=False))
    op.drop_column('users', 'password')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=511), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=511), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
